name: "TeamSpeak3 Server Box"
description: "My first TeamSpeak3 Server add-on!"
version: "1.0.0"
slug: "teamspeak3"
init: true
image: "library/hello-world"
boot: auto
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

