name: "TeamSpeak3 Server Box"
description: "My first TeamSpeak3 Server add-on!"
version: "1.0.0"
slug: "teamspeak3"
boot: auto
startup: application
arch:
  - aarch64
#  - amd64
#  - armhf
#  - armv7
#  - i386

