#file: noinspection All
name: "TeamSpeak3 Server Box"
description: "My first TeamSpeak3 Server add-on!"
version: "1.0.0"
slug: "teamspeak3"
boot: auto
startup: application
arch:
  - aarch64
timeout: 30
ports:
  9987/udp: 9987
  10011/tcp: 10011
  30033/tcp: 30033
ports_description:
  "9987/udp": "Default voice server"
  "10011/tcp": "Server Query"
  "30033/tcp": "File Transfers"
options:
  time_zone: "Europe/Moscow"
  db:
    host: mariadb
    database: teamspeak3
    user: teamspeak
    password: teamspeak
    waituntilready: 30
schema:
  time_zone: str
  db:
    host: str
    database: str
    user: str
    password: str
    waituntilready: int
backup_exclude:
  - ".*/ts3server/logs/.*"