#file: noinspection All
name: "TeamSpeak3 Server Box"
description: "My first TeamSpeak3 Server add-on!"
version: "1.0.0"
slug: "teamspeak3"
boot: auto
init: false
startup: application
arch:
  - aarch64
timeout: 30
map:
  - type: addon_config
    read_only: False
    path: /teamspeak/save
ports:
  9987/udp: 9987
  10011/tcp: 10011
  30033/tcp: 30033
ports_description:
  "9987/udp": "Default voice server"
  "10011/tcp": "Server Query"
  "30033/tcp": "File Transfers"
options:
  time_zone: "Europe/Moscow"
schema:
  time_zone: str
backup_exclude:
  - "*/logs"