#file: noinspection All
---
name: TeamSpeak3 Server Box
version: '0.0.1'
slug: teamspeak
description: TeamSpeak3 Server for Raspberry Pi 4
url: https://github.com/ilyshkafox/DockerContainerAddon/tree/master/teamspeak3-server-box
codenotary: ilya_moslov@mail.ru
ingress: false
startup: services
arch:
  - aarch64
  - armv7
init: false
ports:
  9987/udp: 9987
  10011/tcp: 10011
  30033/tcp: 30033
ports_description:
  9987/udp: Default voice server
  10011/tcp: Server Query
  30033/tcp: File Transfers
map:
  - ssl
options:
  ts_update: true
  time_zone: Europe/Moscow
  db:
    plugin: ts3db_mariadb
    sqlcreatepath: create_mariadb
    host: mariadb
    user: teamspeak
    password: teamspeak
    name: teamspeak3
    waituntilready: 30
schema:
  ts_update: bool
  time_zone: str
  db:
    host: str
    user: str
    password: password
    name: str
    waituntilready: int
services:
  - "mariadb:need"